# Generated by Django 4.1.7 on 2023-04-02 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=50)),
                ('fundacao', models.DateField()),
                ('mascote', models.CharField(default='Nenhum', max_length=30)),
                ('rebaixamento', models.CharField(default='Nenhum', max_length=5)),
                ('principal_titulo', models.CharField(default='Nenhum', max_length=100)),
                ('maior_idolo', models.CharField(default='Nenhum', max_length=100)),
                ('treinador', models.CharField(default='Nenhum', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogador', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('posicao', models.CharField(choices=[('G', 'Goleiro'), ('D', 'Defensor'), ('M', 'Meio Campo'), ('A', 'Atacante')], default='A', max_length=1)),
                ('time_jogador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='times.time')),
            ],
        ),
        migrations.CreateModel(
            name='campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campeonato', models.CharField(max_length=50)),
                ('edicao', models.CharField(default='1', max_length=5)),
                ('artilheiro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='times.jogador')),
                ('campeao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='times.time')),
            ],
        ),
    ]
