# Generated by Django 4.1.7 on 2023-04-02 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='time_jogador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='times.time'),
            preserve_default=False,
        ),
    ]
